import type { Metadata } from "next";
import { Wrapper } from "@/components/Layout";
import "@/styles/globals.css";
import Layout from "@/components/Layout/Layout";

export const metadata: Metadata = {
  title: "To-Do App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Wrapper>
          <Layout>{children}</Layout>
        </Wrapper>
      </body>
    </html>
  );
}
